# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # define go version
  go: "1.19"

  # default concurrency is a available CPU number
  #concurrency: 16

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: true

  # list of build tags, all linters use it. Default is empty list.
  build-tags:
    - netgo

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

linters-settings:
  goimports:
    local-prefixes: github.com/voiplens/mimir-gateway

  errorlint:
    # Check for plain error comparisons.
    comparison: true

    # Do not check for plain type assertions and type switches.
    asserts: false

    # Do not check whether fmt.Errorf uses the %w verb for formatting errors.
    errorf: false

linters:
  enable:
    - goimports
    - revive
    - gofmt
    - unused
    - gosimple
    - misspell
    - errorlint
    - goconst
    - ineffassign
    - unconvert
    - govet
    - typecheck
    - staticcheck
    - errcheck

issues:
  exclude:
    - Error return value of .*log\.Logger\)\.Log\x60 is not checked
    - Error return value of .*.Log.* is not checked
    - Error return value of `` is not checked
