apiVersion: 1
datasources:
  - name: Mimir - Authorization
    access: proxy
    type: prometheus
    url: "http://host.docker.internal:8900/prometheus"
    orgId: 0
    isDefault: false
    jsonData:
      httpHeaderName1: "Authorization"
      prometheusType: Mimir
      prometheusVersion: 2.4.0
    secureJsonData:
      httpHeaderValue1: "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOiJkZXZlbG9wbWVudCIsInZlcnNpb24iOjEsImF1ZCI6InJld2UifQ.a7zdFoVYTk_CKR1Cj3h6S3SBGPseS0x3PNJjy4jdvPtWaraDC638QlXu0CeBMf3vLWPBJB0fopbSMQvm6IoPtw"
  - name: Mimir - OAuth PassThru
    access: proxy
    type: prometheus
    url: "http://host.docker.internal:8900/prometheus"
    orgId: 0
    isDefault: false
    jsonData:
      oauthPassThru: true
      prometheusType: Mimir
      prometheusVersion: 2.4.0
  - name: Loki - Authorization
    access: proxy
    type: loki
    url: "http://host.docker.internal:3100"
    orgId: 0
    isDefault: false
    jsonData:
      httpHeaderName1: "Authorization"
    secureJsonData:
      httpHeaderValue1: "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOiJkZXZlbG9wbWVudCIsInZlcnNpb24iOjEsImF1ZCI6InJld2UifQ.a7zdFoVYTk_CKR1Cj3h6S3SBGPseS0x3PNJjy4jdvPtWaraDC638QlXu0CeBMf3vLWPBJB0fopbSMQvm6IoPtw"
  - name: Loki - OAuth PassThru
    access: proxy
    type: loki
    url: "http://host.docker.internal:3100"
    orgId: 0
    isDefault: false
    jsonData:
      oauthPassThru: true
