version: "3.8"

services:
  agent:
    image: grafana/agent:latest
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/config.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -config.expand-env
      - -config.enable-read-api
    environment:
      HOSTNAME: agent
      REMOTE_WRITE_HOST: host.docker.internal:8900
      OAUTH_CLIENT_ID: $AGENT_CLIENT_ID
      OAUTH_CLIENT_SECRET: $AGENT_CLIENT_SECRET
      OAUTH_TOKEN_URL: $OAUTH_TOKEN_URL
      OAUTH_AUDIENCE: $OAUTH_AUDIENCE
      BEARER_TOKEN: $BEARER_TOKEN
    volumes:
      - ./config/agent.yaml:/etc/agent-config/config.yaml

  promtail:
    image: grafana/promtail:latest
    command:
      - -config.file=/etc/promtail/config.yaml
      - -config.expand-env
    environment:
      HOSTNAME: agent
      REMOTE_WRITE_HOST: host.docker.internal:3100
      OAUTH_CLIENT_ID: $AGENT_CLIENT_ID
      OAUTH_CLIENT_SECRET: $AGENT_CLIENT_SECRET
      OAUTH_TOKEN_URL: $OAUTH_TOKEN_URL
      OAUTH_AUDIENCE: $OAUTH_AUDIENCE
      BEARER_TOKEN: $BEARER_TOKEN
    volumes:
      - ./config/promtail.yaml:/etc/promtail/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock

  minio:
    image: minio/minio
    entrypoint: [""]
    command:
     - "sh"
     - "-euc"
     - |
       mkdir -p /data/mimir && \
       mkdir -p /data/loki-data && \
       mkdir -p /data/loki-ruler && \
       minio server --quiet /data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    volumes:
      - minio-data:/data

  mimir:
    image: grafana/mimir:latest
    command:
      - -config.file=/etc/mimir.yaml
    depends_on:
      - minio
    hostname: mimir
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - ./config/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - mimir-data:/data
    ports:
      - "9009:8080"

  loki:
    image: grafana/loki:latest
    command:
      - -config.file=/etc/loki.yaml
    depends_on:
      - minio
    hostname: loki
    volumes:
      - ./config/loki.yaml:/etc/loki.yaml
      - loki-data:/data
    ports:
      - "3101:3100"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./config/grafana-provisioning-datasources.yaml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml:ro
    user: "104"
    ports:
      - 3000:3000
    restart: always
    environment:
      GF_LOG_LEVEL: "debug"
      GF_APP_MODE: "development"
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_AUTO_ASSIGN_ORG_ROLE: "Viewer"
      GF_USERS_VIEWERS_CAN_EDIT: "false"
      GF_SMTP_ENABLED: "false"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_OAUTH_AUTO_LOGIN: "true"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "Auth0"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_USE_PKCE: "true"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: $GRAFANA_ROLE_ATTRIBUTE_PATH
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: $GRAFANA_CLIENT_ID
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: $GRAFANA_CLIENT_SECRET
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: $OAUTH_AUTH_URL
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: $OAUTH_TOKEN_URL
      GF_AUTH_GENERIC_OAUTH_API_URL: $OAUTH_API_URL

volumes:
  minio-data:
  mimir-data:
  loki-data:
